# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

  create_table "clips", :force => true do |t|
    t.string   "title"
    t.string   "location"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "featured",   :default => false
  end

  create_table "playlists", :force => true do |t|
    t.integer "user_id"
    t.string  "title"
    t.string  "info"
    t.string  "annotation"
  end

  create_table "tracks", :force => true do |t|
    t.integer "playlist_id"
    t.string  "title"
    t.string  "creator"
    t.string  "location"
    t.string  "info"
    t.string  "image"
    t.string  "identifier"
    t.string  "album"
  end

  create_table "users", :force => true do |t|
    t.string   "login"
    t.string   "email"
    t.string   "crypted_password",          :limit => 40
    t.string   "salt",                      :limit => 40
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "remember_token"
    t.datetime "remember_token_expires_at"
    t.string   "activation_code",           :limit => 40
    t.datetime "activated_at"
    t.integer  "playlist_id"
  end

end
